import './globals.css';
import { Inter } from 'next/font/google';
// import Nav from './components/Nav';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <body className={inter.className}>
          {children}

      </body>
    </html>
  );
}
